import os

def sobre_trabalho():
    os.system("cls")
    print("""
        SOBRE: 
        SHARRING BOOKS


        ESTE SISTEMA TEM POR OBJETIVO GERENCIAR O EMPRÉSTIMO DE LIVROS LOCALIZADOS EM PONTOS ESPALHADOS PELA CIDADE.
        O SHARRING BOOKS FOI DESENVOLVIDO UTILIZANDO A LINGUAGEM PYTHON.
        OS DADOS SÃO ARMAZENADOS NO SGBD PostgreSQL.


        ALUNOS:
            RODOLFO DANTAS QUEIROZ - RA 2840482013026
            THIERRY YAGO COSSALTER TEIXEIRA - RA 2840481821031

        PROFESSOR:
            PROF. ME. FABRÍCIO GUSTAVO HENRIQUE
    """)